service: meter

provider:
  name: aws
  runtime: nodejs10.x

plugins:
- serverless-webpack

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        method: get
        path: hello

